name: Packer Custom Image Build

on: 
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Packer Custom Image Build

    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SECURITY_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ secrets.POSTGRES_USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          database: ${{ secrets.POSTGRES_DATABASE }}
          port: 5432
        id: postgres

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.7'
      
      - name: 'Set db from repo secret'
        run: |
          jq '.PASSWORD = $newVal' --arg newVal '${{ secrets.POSTGRES_PASSWORD }}' app/config/db.config.json > tmp.$$.json && mv tmp.$$.json app/config/db.config.json

      - run: npm ci
      - run: npm test

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: '1.10.1'

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt ."

      - name: Run `zip`
        id: zip
        run: "zip -r webapp.zip ./app build.pkr.hcl build.sh csye6225.service package.json package-lock.json server.js variables.pkrvars.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."        

      - name: Run `packer build`
        id: build
        run: |
          packer build -parallel-builds=1 -var "gcp_service_acc_key=${{ secrets.GCP_SECURITY_CREDENTIALS}}" build.pkr.hcl
