name: Webapp Tests CI

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Webapp Tests CI job

    runs-on: ubuntu-latest

    steps:
      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ secrets.POSTGRES_USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          database: ${{ secrets.POSTGRES_DATABASE }}
          port: 5432
        id: postgres
      # - run: pytest -vv tests/
      #   env:
      #     CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}
      # - run: pytest -vv tests/
      #   env:
      #     CONNECTION_STR: service=${{ steps.postgres.outputs.service-name }}

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.7'
      
      - name: 'Set db from repo secret'
        run: |
          jq '.PASSWORD = $newVal' --arg newVal '${{ secrets.POSTGRES_PASSWORD }}' app/config/db.config.json > tmp.$$.json && mv tmp.$$.json app/config/db.config.json

      - run: npm ci
      - run: touch webapp.log
      - run: ENVI='TEST' LOG_PATH='webapp.log' npm test
